# Generated by Django 3.0.5 on 2020-04-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='this is a test description hhdjdsvk isbks bksbl sbs jksbl kk bkf bbk bkf'),
            preserve_default=False,
        ),
    ]
