# Generated by Django 3.0.5 on 2020-04-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_coupon_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='amount',
        ),
    ]
